// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {SafeTransferLib} from '@solady/utils/SafeTransferLib.sol';


import {IPoolManager} from '@uniswap/v4-core/src/interfaces/IPoolManager.sol';
import {Hooks, IHooks} from '@uniswap/v4-core/src/libraries/Hooks.sol';
import {SafeCast} from '@uniswap/v4-core/src/libraries/SafeCast.sol';
import {StateLibrary} from '@uniswap/v4-core/src/libraries/StateLibrary.sol';
import {BalanceDelta} from '@uniswap/v4-core/src/types/BalanceDelta.sol';
import {BeforeSwapDelta, BeforeSwapDeltaLibrary, toBeforeSwapDelta} from '@uniswap/v4-core/src/types/BeforeSwapDelta.sol';

import {Currency} from '@uniswap/v4-core/src/types/Currency.sol';
import {PoolId, PoolIdLibrary} from '@uniswap/v4-core/src/types/PoolId.sol';
import {PoolKey} from '@uniswap/v4-core/src/types/PoolKey.sol';
import {ModifyLiquidityParams, SwapParams} from '@uniswap/v4-core/src/types/PoolOperation.sol';

import {FeeDistributor} from '@flaunch/hooks/FeeDistributor.sol';
import {Notifier} from '@flaunch/hooks/Notifier.sol';
import {UnlockingHook} from '@flaunch/hooks/UnlockingHook.sol';
import {CurrencySettler} from '@flaunch/libraries/CurrencySettler.sol';
import {FlaunchLibrary} from '@flaunch/libraries/FlaunchLibrary.sol';
import {TreasuryActionManager} from '@flaunch/treasury/ActionManager.sol';
import {MemecoinTreasury} from '@flaunch/treasury/MemecoinTreasury.sol';
import {MemecoinFinder} from '@flaunch/types/MemecoinFinder.sol';
import {
    TS_ISP_AMOUNT0,
    TS_ISP_AMOUNT1,
    TS_ISP_FEE0,
    TS_ISP_FEE1,
    TS_UNI_AMOUNT0,
    TS_UNI_AMOUNT1,
    TS_UNI_FEE0,
    TS_UNI_FEE1
} from '@flaunch/types/StoreKeys.sol';

import {IBidWall} from '@flaunch-interfaces/IBidWall.sol';
import {IFeeCalculator} from '@flaunch-interfaces/IFeeCalculator.sol';
import {IFeeExemptions} from '@flaunch-interfaces/IFeeExemptions.sol';
import {IFlaunch} from '@flaunch-interfaces/IFlaunch.sol';
import {IInitialPrice} from '@flaunch-interfaces/IInitialPrice.sol';
import {IInternalSwapPool} from '@flaunch-interfaces/IInternalSwapPool.sol';
import {IMemecoin} from '@flaunch-interfaces/IMemecoin.sol';
import {IOracle} from '@flaunch-interfaces/IOracle.sol';
import {IPairedTokenRegistry} from '@flaunch-interfaces/IPairedTokenRegistry.sol';
import {IPositionManager} from '@flaunch-interfaces/IPositionManager.sol';

/**
 * The PositionManager is a Uniswap V4 hook that controls the user journey from token creation
 * to ongoing swaps.
 *
 * The creator of the pool will receive an ERC721 representation of the token. The holder of
 * this token will be the recipient of any creator fees generated by the token in the pool.
 *
 * Hook interactions have aimed to be abstracted into inherited contracts to simplify both
 * functionality and readability. Specific use of each of these contracts has been denoted
 * within comments using square brackets where possible.
 */
contract PositionManager is UnlockingHook, FeeDistributor, IPositionManager {
    using BeforeSwapDeltaLibrary for BeforeSwapDelta;
    using CurrencySettler for Currency;
    using PoolIdLibrary for PoolKey;
    using SafeCast for uint;
    using StateLibrary for IPoolManager;
    using MemecoinFinder for PoolKey;

    /// Identifies the action a {PoolManager} `unlock` callback should perform
    enum UnlockCallbackType {
        CLOSE_BIDWALL,
        FLAUNCH_LIQUIDITY
    }

    /// The minimum amount before a distribution is triggered
    uint public constant MIN_DISTRIBUTE_THRESHOLD = 0.001 ether;

    /// The contract that will be used for flaunching tokens
    IFlaunch public flaunchContract;

    /// Our starting token sqrtPriceX96
    IInitialPrice public initialPrice;

    /**
     * Internal storage to allow the `beforeSwap` tick value to be used in `afterSwap`.
     *
     * @dev This is ONE slot shared by every pool, so it is only trustworthy between a swap's own
     * `beforeSwap` and the first external call its `afterSwap` makes. `PoolManager.swap` is
     * `onlyWhenUnlocked` with no reentrancy guard and the outer unlock is still held, so any call
     * out to token code -- the referrer transfer in {_captureAndDepositFees}, or `_allocateFees`
     * inside {_distributeFees} -- can re-enter with a nested swap whose `beforeSwap` overwrites
     * this slot before the outer swap has read it.
     *
     * Two rules keep it trustworthy, and both are needed:
     *
     *   - {_beforeSwap} holds the tick in a local across `checkStalePosition` and the oracle, and
     *     COMMITS here last, after every external call it makes. A stale reposition moves tokens,
     *     so a callback-capable token can nest a swap inside `beforeSwap` itself -- before this
     *     swap has even reached `afterSwap`.
     *   - {_afterSwap} SNAPSHOTS it into a local on its first line and threads that value down to
     *     the {BidWall} deposit, instead of re-reading storage after its own callbacks.
     *
     * Transient storage would not fix this on its own: the slot is shared across pools, so it
     * would have to be keyed by `PoolId`, and a nested swap on the SAME pool would still clobber
     * it.
     */
    int24 internal _beforeSwapTick;

    /// Store the address that will collect protocol fees
    address internal protocolFeeRecipient;

    /// Store the contract that will manage our Bidwall interactions
    IBidWall public bidWall;

    /// The contract that handles the token Treasury actions
    TreasuryActionManager public actionManager;

    /// Store the contract that will manage fee exemptions
    IFeeExemptions public feeExemptions;

    /// Store our {Notifier} contract
    Notifier public notifier;

    /// The price {Oracle} used to price internal fills
    IOracle public immutable oracle;

    /// The shared {InternalSwapPool} that holds fee inventory + the price oracle for our pools
    IInternalSwapPool public internalSwapPool;

    /// The owner-controlled whitelist + per-token config for selectable paired tokens
    IPairedTokenRegistry public pairedTokenRegistry;

    /// A pool's paired token, recorded at launch. `set` is the authoritative "has this pool been
    /// launched here" signal. It cannot be inferred from the token address, because native ETH
    /// (`token == address(0)`) is a real selection — without `set`, an unknown pool queried
    /// through {pairedToken} would be indistinguishable from a native-ETH pool. Every pool this
    /// hook serves has `set == true`: `_beforeInitialize` blocks foreign pools, and
    /// `_initializeLaunchedPool` writes the record for every flaunch. The two fields pack into a
    /// single storage slot.
    struct PoolPairedToken {
        address token;
        bool set;
    }

    /// Maps a pool to its recorded paired token (see {PoolPairedToken}).
    mapping(PoolId _poolId => PoolPairedToken _pairedToken) internal _pairedToken;

    /**
     * Per-pool snapshot of a paired token's registry config, captured once at launch. Fee-routing
     * and threshold decisions read this frozen snapshot instead of the live registry, so a later
     * `unapprovePairedToken` or reconfigure in the registry cannot retroactively change how an
     * already-launched pool routes fees or applies thresholds (VPT-12 freezes the escrow and
     * thresholds). The unwrap policy applied at payout time is deliberately NOT snapshotted: it is
     * resolved from the LIVE registry by {PairedTokenLib.payout}, so the registry stays the single
     * source of truth for what each token unwraps to. The `tokenType` and `feeEscrow` members pack
     * into a single storage slot.
     *
     * @member tokenType The paired token's shape (see {IPairedTokenRegistry.PairedTokenType}); a
     * native wrapper premine funds from ETH and unwraps to ETH, an ERC20 wrapper (flUSDC) does not
     * @member feeEscrow The {FeeEscrow} this pool's fees route through
     * @member minDistribute The minimum paired-token fee inventory before the pool distributes
     * @member bidWallThreshold The accumulated-fee threshold before the BidWall repositions
     */
    struct PairedTokenConfig {
        IPairedTokenRegistry.PairedTokenType tokenType;
        address feeEscrow;
        uint minDistribute;
        uint bidWallThreshold;
    }

    /// Frozen-at-launch snapshot of each pool's paired-token config (see {PairedTokenConfig}).
    /// Written for every pool this hook serves (`_initializeLaunchedPool`); resolvers revert
    /// `UnknownPool` for anything else rather than guessing a default.
    mapping(PoolId _poolId => PairedTokenConfig _config) internal _pairedTokenConfig;

    /// Store the block timestamp when a poolId is set to launch
    mapping(PoolId _poolId => uint _flaunchTime) public flaunchesAt;

    /// Stores the tick the pool was initialized at, captured from `poolManager.initialize`. Used
    /// by fee calculators (e.g. {TrustedSignerFeeCalculator}) to quote against the launch price
    mapping(PoolId _poolId => int24 _initialTick) public initialPoolTick;

    /**
     * Initializes our {BaseHook} contract and initializes all implemented hooks.
     */
    constructor(
        ConstructorParams memory params
    )
        UnlockingHook(params.poolManager)
        FeeDistributor(params.feeDistribution, params.protocolOwner, params.flayGovernance)
    {
        // Set our contract references
        initialPrice = params.initialPrice;

        // Set our protocol fee recipient
        protocolFeeRecipient = params.protocolFeeRecipient;

        // Register our FeeExemption contract
        feeExemptions = params.feeExemptions;

        // Register our BidWall contract
        bidWall = params.bidWall;

        // Register our ActionManager
        actionManager = TreasuryActionManager(address(params.actionManager));

        // Register our shared InternalSwapPool
        internalSwapPool = params.internalSwapPool;

        // Register our shared price Oracle
        oracle = params.oracle;

        // Register our paired token whitelist + config
        pairedTokenRegistry = params.pairedTokenRegistry;

        // Deploy our notifier
        notifier = new Notifier(params.protocolOwner);
    }

    /**
     * Creates a new ERC20 memecoin token creating and an ERC721 that signifies ownership of the
     * flaunched collection. The token is then initialized into a UV4 pool.
     *
     * @param _params The parameters for the flaunch
     *
     * @return memecoin_ The created ERC20 token address
     */
    function flaunch(
        FlaunchParams calldata _params
    ) external payable returns (address memecoin_) {
        return _flaunch(_params, 0);
    }

    /**
     * {flaunch}, bounding what a pull-funded (ERC20-paired) premine may cost the caller.
     *
     * @dev The premine is priced from the pool's launch price, which resolves through the paired
     * token's registered price calculator when the transaction executes — not when it is signed. On
     * the ETH-funded shapes `msg.value` already bounds that exposure, but a pull-funded premine is
     * bounded only by the allowance the caller granted this contract, so a caller holding a broad
     * approval can be charged more than they quoted if the oracle moves or the calculator is
     * rotated in between. This overload lets them declare the cap explicitly.
     *
     * `_maxPremineCost` is ignored for ETH-funded and no-premine launches, which have no paired
     * token to pull.
     *
     * @param _params The parameters for the flaunch
     * @param _maxPremineCost The most paired token the premine may cost (`0` = uncapped)
     *
     * @return memecoin_ The created ERC20 token address
     */
    function flaunch(
        FlaunchParams calldata _params,
        uint _maxPremineCost
    ) external payable returns (address memecoin_) {
        return _flaunch(_params, _maxPremineCost);
    }

    /**
     * The shared launch routine behind both {flaunch} entrypoints.
     *
     * @param _params The parameters for the flaunch
     * @param _maxPremineCost The most paired token a pull-funded premine may cost (`0` = uncapped)
     *
     * @return memecoin_ The created ERC20 token address
     */
    function _flaunch(
        FlaunchParams calldata _params,
        uint _maxPremineCost
    ) internal returns (address memecoin_) {
        uint tokenId;
        address payable memecoinTreasury;
        PoolId poolId;
        bool currencyFlipped;

        // Flaunch our token to create the memecoin and memecoin treasury
        (memecoin_, memecoinTreasury, tokenId) = flaunchContract.flaunch(_params);

        // Check if we have an initial flaunching fee, check that enough ETH has been sent
        uint flaunchFee = getFlaunchingFee(_params.initialPriceParams);

        uint remainingValue = msg.value;

        // Collect the launch fee first.
        if (flaunchFee != 0) {
            if (remainingValue < flaunchFee) {
                revert InsufficientFlaunchFee(remainingValue, flaunchFee);
            }

            remainingValue -= flaunchFee;

            // Transfer the flaunching fee to the protocol fee recipient
            SafeTransferLib.safeTransferETH(protocolFeeRecipient, flaunchFee);
        }

        // Initialize the pool and store the pool key and currency flipped
        (poolId, currencyFlipped) = _initializeLaunchedPool(memecoin_, memecoinTreasury, _params);

        // Emit in a separate frame: encoding the full FlaunchParams struct for the event is
        // stack-heavy and would otherwise tip this frame over the legacy stack limit.
        _emitPoolCreated(poolId, memecoin_, memecoinTreasury, tokenId, currencyFlipped, flaunchFee, _params);

        // Seed the pool's initial single-sided liquidity (and fill the premine, if any) inside a
        // {PoolManager} unlock, as creating positions requires the unlock context. We also process
        // any premine / prebuy calculations inside of this unlock callback.
        // The unlock returns the ETH consumed by the premine (zero for an ERC20-paired premine,
        // which is funded by pulling the paired token from the caller instead of msg.value).
        remainingValue -= abi.decode(
            poolManager.unlock(
                abi.encode(
                    UnlockCallbackType.FLAUNCH_LIQUIDITY,
                    abi.encode(memecoin_, _params.creator, msg.sender, _params.premineAmount, remainingValue, _maxPremineCost)
                )
            ),
            (uint)
        );

        // Refund any remaining ETH that was not required
        if (remainingValue != 0) {
            SafeTransferLib.safeTransferETH(msg.sender, remainingValue);
        }

        // After our contract is initialized, emit our pool state update to notify the UX of
        // current prices and fees.
        _emitPoolStateUpdate(poolId, IHooks.afterInitialize.selector, abi.encode(tokenId, _params));
    }

    /**
     * Emits {PoolCreated} in its own frame so the full FlaunchParams encoding does not deepen the
     * {flaunch} stack frame.
     */
    function _emitPoolCreated(
        PoolId _poolId,
        address _memecoin,
        address _memecoinTreasury,
        uint _tokenId,
        bool _currencyFlipped,
        uint _flaunchFee,
        FlaunchParams calldata _params
    ) internal {
        emit PoolCreated({
            _poolId: _poolId,
            _memecoin: _memecoin,
            _memecoinTreasury: _memecoinTreasury,
            _tokenId: _tokenId,
            _currencyFlipped: _currencyFlipped,
            _flaunchFee: _flaunchFee,
            _params: _params
        });
    }

    /**
     * Initializes the pool for a launched memecoin.
     *
     * @param _memecoin The address of the memecoin
     * @param _memecoinTreasury The address of the memecoin treasury
     * @param _params The parameters for the flaunch
     *
     * @return poolId_ The ID of the pool
     * @return currencyFlipped_ Whether the currency is flipped
     */
    function _initializeLaunchedPool(
        address _memecoin,
        address payable _memecoinTreasury,
        FlaunchParams calldata _params
    ) internal returns (PoolId poolId_, bool currencyFlipped_) {
        // Resolve + validate the paired token in a separate frame so the registry call's ABI
        // decode does not deepen this (stack-sensitive) launch frame.
        address pairedToken_ = _resolvePairedToken(_memecoin, _params.pairedToken);

        // Determine if the currency is flipped
        currencyFlipped_ = pairedToken_ >= _memecoin;

        // Create the pool key
        PoolKey memory poolKey_ = PoolKey({
            currency0: Currency.wrap(!currencyFlipped_ ? pairedToken_ : _memecoin),
            currency1: Currency.wrap(currencyFlipped_ ? pairedToken_ : _memecoin),
            fee: 0,
            tickSpacing: 60,
            hooks: IHooks(address(this))
        });

        // Initialize the memecoin treasury against the pool's paired token
        MemecoinTreasury(_memecoinTreasury).initialize(payable(address(this)), address(actionManager), pairedToken_, poolKey_);

        // Store the pool key
        _poolKeys[_memecoin] = poolKey_;

        // Store the pool ID
        poolId_ = poolKey_.toId();

        // Record the pool's paired token so every downstream fee / liquidity / distribution path
        // resolves the correct side instead of assuming the global native token
        _pairedToken[poolId_] = PoolPairedToken({token: pairedToken_, set: true});

        // Freeze the paired token's registry config into this pool. From here on the pool reads its
        // own snapshot (escrow / thresholds / unwrap behaviour), so a later registry unapprove or
        // reconfigure cannot retroactively change how this live pool behaves (VPT-12). Kept in its
        // own frame so the registry call's ABI decode does not deepen this stack-sensitive frame.
        _snapshotPairedTokenConfig(poolId_, pairedToken_);

        // Ensure the BidWall can pull this pool's paired token (flETH, flUSDC, ...) from the hook.
        // Every pool's approval is granted lazily here at launch — there is no constructor-time
        // special case for any token. Kept in the linked library so the allowance call's ABI
        // decode stays out of this hook.
        FlaunchLibrary.ensureBidWallApproval(address(bidWall), pairedToken_);

        /**
         * If the token is scheduled to flaunch in the future, store the timestamp so that
         * `_beforeSwap` can gate public swaps until the schedule has passed. A premine is exempt
         * from this as it is filled internally during `flaunch`, not via `_beforeSwap`.
         *
         * [L-6] That exemption is NOT a property of this contract -- it is inherited from Uniswap
         * v4, and it is load-bearing enough to state explicitly.
         *
         * `Hooks.beforeSwap` and `Hooks.afterSwap` return early when `msg.sender == address(self)`
         * (`Hooks.sol:253`, `:293`), so a swap this hook issues itself fires NO hook callbacks at
         * all. The premine swap is issued by this hook, so it never reaches the schedule gate --
         * and it also never reaches fee capture, fee distribution, the {InternalSwapPool} or the
         * oracle. At least eight correctness properties rest on that single upstream behaviour,
         * including premine refund accounting and ISP backing, and none of them are enforced here.
         *
         * The practical consequence: a future refactor that routes the premine through a router,
         * a zap, or any other non-hook caller would silently re-enable every one of those
         * callbacks. Scheduling would reject the premine, the refund maths would change, and the
         * ISP would take inventory it has no backing for -- all at once, with no revert to point
         * at. Anything moving the premine off this hook's own `msg.sender` must re-derive these
         * properties from scratch rather than assume they still hold.
         */
        if (_params.flaunchAt > block.timestamp) {
            flaunchesAt[poolId_] = _params.flaunchAt;
            emit PoolScheduled(poolId_, _params.flaunchAt);
        }

        // Store the creator fee allocation
        if (_params.creatorFeeAllocation != 0) {
            creatorFee[poolId_] = _params.creatorFeeAllocation;
        }

        // Initialize the pool at its starting price and cache the resulting tick so fee
        // calculators can later quote swaps against the launch price
        initialPoolTick[poolId_] =
            poolManager.initialize(poolKey_, initialPrice.getSqrtPriceX96(msg.sender, currencyFlipped_, pairedToken_, _params.initialPriceParams));

        // [F-7] Seed the price Oracle's ring buffer with the initial tick so that the very first
        // {InternalSwapPool} fill (and any other TWAP consumer) is priced from oracle history,
        // never from slot0. Without this seed, the `twapTick()` warm-up branch returns the spot
        // tick on the first observation, which can be moved atomically within the same swap.
        oracle.recordObservation(poolId_, initialPoolTick[poolId_]);

        // Initialize the fee calculators
        _initializeFeeCalculators(poolId_, _params.feeCalculatorParams);
    }

    /**
     * Returns the PoolKey mapped to the token address. If none is set then a zero value
     * will be returned for the fields.
     *
     * @dev The easiest way to check for an empty response is `tickSpacing = 0`
     *
     * @param _token The address of the ERC20 token
     *
     * @return The corresponding {PoolKey} for the token
     */
    function poolKey(
        address _token
    ) external view returns (PoolKey memory) {
        return _poolKeys[_token];
    }

    /**
     * Returns the token a pool's memecoin is paired against.
     *
     * @dev Reverts for a pool this hook never launched, rather than guessing: returning the raw
     * record would report `address(0)` — a claim of "native ETH pool" — for a pool that does not
     * exist, since the zero address is a real selection.
     *
     * @param _poolId The pool to resolve the paired token for
     *
     * @return pairedToken_ The pool's paired token (`address(0)` = native ETH)
     */
    function pairedToken(
        PoolId _poolId
    ) public view returns (address pairedToken_) {
        PoolPairedToken storage p = _pairedToken[_poolId];
        if (!p.set) revert UnknownPool(_poolId);
        pairedToken_ = p.token;
    }

    /**
     * The authoritative {FeeEscrow} a pool's fees route through, read from the pool's launch-time
     * snapshot. Downstream integrations (e.g. the memecoin treasury's `claimFees`) resolve the
     * correct escrow through this getter rather than assuming the global flETH escrow.
     *
     * @dev Reverts `UnknownPool` for a pool this hook never launched — every launched pool has a
     * snapshot with a registry-guaranteed, non-zero escrow.
     *
     * @param _poolId The pool to resolve the fee escrow for
     *
     * @return escrow_ The {FeeEscrow} the pool's fees route through
     */
    function pairedTokenFeeEscrow(
        PoolId _poolId
    ) public view returns (address escrow_) {
        (, escrow_) = _resolveFeeEscrow(_poolId);
    }

    /**
     * The BidWall reposition threshold for a pool, read from its launch-time snapshot rather than
     * the live registry. Resolving from the snapshot means unapproving / reconfiguring the paired
     * token in the registry cannot degrade an existing pool's plunge protection (a `0` here means
     * "use the BidWall's protocol default").
     *
     * @param _poolId The pool whose BidWall threshold is being resolved
     *
     * @return threshold_ The snapshotted BidWall threshold (0 = use the BidWall default)
     */
    function pairedTokenBidWallThreshold(
        PoolId _poolId
    ) public view returns (uint threshold_) {
        threshold_ = _pairedTokenConfig[_poolId].bidWallThreshold;
    }

    /**
     * Snapshots a paired token's registry config into a pool at launch (VPT-12). Reads the registry
     * exactly once here; every later fee-routing / threshold / unwrap decision for the pool reads
     * the stored snapshot instead of the live registry.
     *
     * @param _poolId The pool being launched
     * @param _pairedTokenAddress The pool's resolved paired token
     */
    function _snapshotPairedTokenConfig(
        PoolId _poolId,
        address _pairedTokenAddress
    ) internal {
        IPairedTokenRegistry.PairedToken memory config = pairedTokenRegistry.tokenConfig(_pairedTokenAddress);
        _pairedTokenConfig[_poolId] = PairedTokenConfig({
            tokenType: config.tokenType,
            feeEscrow: config.feeEscrow,
            minDistribute: config.minDistribute,
            bidWallThreshold: config.bidWallThreshold
        });
    }

    /**
     * The minimum paired-token fee inventory required before a pool distributes. Read from the
     * pool's launch-time snapshot (decimals-aware per paired token), falling back to the protocol
     * default that preserves existing flETH behaviour when the snapshot leaves it at 0.
     *
     * @param _poolId The pool whose distribution threshold is being resolved
     *
     * @return threshold_ The minimum distributable amount in the pool's paired-token units
     */
    function _minDistributeThreshold(
        PoolId _poolId
    ) internal view returns (uint threshold_) {
        threshold_ = _pairedTokenConfig[_poolId].minDistribute;
        if (threshold_ == 0) {
            threshold_ = MIN_DISTRIBUTE_THRESHOLD;
        }
    }

    /**
     * Routes a pool's fees through the {FeeEscrow} snapshotted for its paired token at launch, so
     * flUSDC fees land in the flUSDC escrow and flETH fees in the flETH escrow. The escrow is read
     * from the pool's frozen snapshot (never the live registry), so unapproving / reconfiguring the
     * token afterwards cannot re-route an existing pool's fees (VPT-12).
     *
     * @dev The global flETH escrow fallback is intentionally restricted to the native token
     * (VPT-6): the registry now guarantees a matched escrow at approve-time and the snapshot
     * captures it at launch, so any non-native pool with a zero snapshot escrow is a
     * misconfiguration and must revert rather than silently drain / strand into the flETH escrow.
     *
     * @param _poolId The pool whose fee routing is being resolved
     *
     * @return token_ The pool's paired token
     * @return escrow_ The {FeeEscrow} the pool's fees route through
     */
    function _resolveFeeEscrow(
        PoolId _poolId
    ) internal view override returns (address token_, address escrow_) {
        token_ = pairedToken(_poolId);

        // The registry guarantees a non-zero, token-matched escrow at approval and the launch
        // snapshot copies it in the same transaction, so a zero here is snapshot corruption:
        // revert rather than let fees route to (and burn at) the zero address.
        escrow_ = _pairedTokenConfig[_poolId].feeEscrow;
        if (escrow_ == address(0)) {
            revert MissingPairedTokenEscrow(token_);
        }
    }

    /**
     * Resolves the paired token for a launch and validates it. The selection is used verbatim —
     * there is no implicit default — so it must be whitelisted in the registry and must not collide
     * with the memecoin. `address(0)` is a real selection (native ETH); a launcher wanting flETH
     * must pass flETH's address explicitly.
     *
     * @param _memecoin The memecoin being launched
     * @param _selected The launcher's selected paired token (`address(0)` = native ETH, once approved)
     *
     * @return pairedToken_ The validated paired token for the pool
     */
    function _resolvePairedToken(
        address _memecoin,
        address _selected
    ) internal view returns (address pairedToken_) {
        // There is no implicit default: the selection is used verbatim and must be approved. This
        // is what lets `address(0)` mean real native ETH (once it is registered) rather than an
        // alias for flETH — a launcher wanting flETH must pass flETH's address explicitly.
        pairedToken_ = _selected;
        if (!pairedTokenRegistry.isApproved(pairedToken_)) {
            revert PairedTokenNotApproved(pairedToken_);
        }
        if (pairedToken_ == _memecoin) {
            revert PairedTokenIsMemecoin();
        }
    }

    /**
     * Pass-through getter for a pool's {InternalSwapPool} claimable fees, kept on the
     * {PositionManager} for integrations that previously read fees directly from the hook.
     *
     * @param _poolKey The PoolKey to check
     */
    function poolFees(
        PoolKey memory _poolKey
    ) external view returns (IInternalSwapPool.ClaimableFees memory) {
        return internalSwapPool.poolFees(_poolKey);
    }

    /**
     * Defines the Uniswap V4 hooks that are used by our implementation. This will determine
     * the address that our contract **must** be deployed to for Uniswap V4. This address suffix
     * is shown in the dev comments for this function call.
     *
     * @dev 10 0101 1101 1100 == 25DC
     */
    function getHookPermissions() public pure override returns (Hooks.Permissions memory) {
        return Hooks.Permissions({
            beforeInitialize: true, // Prevent initialize
            afterInitialize: false,
            beforeAddLiquidity: false,
            afterAddLiquidity: true, // [EventTracking]
            beforeRemoveLiquidity: false,
            afterRemoveLiquidity: true, // [EventTracking]
            beforeSwap: true, // [InternalSwapPool]
            afterSwap: true, // [FeeDistributor], [InternalSwapPool], [BidWall], [EventTracking]
            beforeDonate: false,
            afterDonate: true, // [EventTracking]
            beforeSwapReturnDelta: true, // [InternalSwapPool]
            afterSwapReturnDelta: true, // [FeeDistributor]
            afterAddLiquidityReturnDelta: false,
            afterRemoveLiquidityReturnDelta: false
        });
    }

    /**
     * The hook called before the state of a pool is initialized. Prevents external contracts
     * from initializing pools using our contract as a hook.
     *
     * @dev As we call `poolManager.initialize` from the IHooks contract itself, we bypass this
     * hook call as therefore bypass the prevention.
     */
    function _beforeInitialize(
        address,
        PoolKey calldata,
        uint160
    ) internal pure override returns (bytes4) {
        revert CannotBeInitializedDirectly();
    }

    /**
     * [ISP] Checks if we can process an internal swap ahead of the Uniswap swap.
     * [FD] Captures fees from the internal swap pool
     *
     * @param _sender The address calling the swap
     * @param _key The key for the pool
     * @param _params The parameters for the swap
     * @param _hookData Arbitrary data handed into the PoolManager by the swapper to be be passed on to the hook
     *
     * @return selector_ The function selector for the hook
     * @return beforeSwapDelta_ The hook's delta in specified and unspecified currencies. Positive: the hook is
     * owed/took currency, negative: the hook owes/sent currency
     * @return swapFee_ The percentage fee applied to our swap
     */
    function _beforeSwap(
        address _sender,
        PoolKey calldata _key,
        SwapParams calldata _params,
        bytes calldata _hookData
    ) internal override returns (bytes4 selector_, BeforeSwapDelta beforeSwapDelta_, uint24) {
        PoolId poolId = _key.toId();

        /**
         * [SCHEDULE] Check if the token is scheduled to be flaunched.
         */

        // If set, get the timestamp that the pool is scheduled to flaunch
        uint _flaunchesAt = flaunchesAt[poolId];
        if (_flaunchesAt != 0) {
            // If we have a schedule set for the token, then we need to make an additional
            // check to see if a premine is set, and if it's valid. If the timestamp has not
            // yet passed, then we revert.
            if (_flaunchesAt > block.timestamp) {
                revert TokenNotFlaunched(_flaunchesAt);
            }

            // Remove the schedule timestamp to prevent future checks
            delete flaunchesAt[poolId];
        }

        // Resolve the paired side inline (direct mapping read, no call frame) to keep this
        // stack-sensitive swap entrypoint within the stack limit. Every pool that can reach a
        // swap was launched here, so the record is always set.
        bool nativeIsZero = Currency.unwrap(_key.currency0) == _pairedToken[poolId].token;

        /**
         * [ISP] We want to see if we have any token1 fee tokens that we can use to fill the swap
         * before it hits the Uniswap pool. This prevents the pool from being affected and reduced
         * gas costs. This also allows us to benefit from the Uniswap routing infrastructure.
         *
         * This frontruns Uniswap to sell undesired token amounts from our fees into desired tokens
         * ahead of our fee distribution. This acts as a partial orderbook to remove impact against
         * our pool.
         */
        beforeSwapDelta_ = _processInternalSwap(_sender, _key, _params, _hookData, nativeIsZero, beforeSwapDelta_);

        /**
         * Capture the beforeSwap tick value before actioning our Uniswap swap.
         *
         * Held as a LOCAL for everything below, and committed to the shared slot only once every
         * external call is done. `checkStalePosition` can reposition, and a reposition moves
         * tokens -- the paired-token pay-back to this hook, the settle, and the memecoin push to
         * the treasury are all uncapped calls into token code. A callback-capable token can run a
         * nested swap from any of them, and that nested swap's own `beforeSwap` writes the shared
         * slot. Writing ours first meant the nested value survived, so this swap's `afterSwap`
         * would read a tick belonging to a different pool -- and the oracle below would record it.
         *
         * Committing last makes the ordering self-correcting: a nested swap writes and consumes
         * its own tick entirely inside this call, and we overwrite it with ours on the way out.
         */
        (, int24 beforeSwapTick,,) = poolManager.getSlot0(poolId);

        // Check if the BidWall has become stale, and allow liquidity to be extracted before a
        // threshold has been built.
        bidWall.checkStalePosition(_key, beforeSwapTick, nativeIsZero);

        // Record the pre-swap tick into the price oracle (at most once per block) on every swap,
        // regardless of direction or inventory, so the TWAP reference stays fresh.
        oracle.recordObservation(poolId, beforeSwapTick);

        // Commit the tick for `_afterSwap`. Last, and after every call above.
        _beforeSwapTick = beforeSwapTick;

        // Set our return selector
        selector_ = IHooks.beforeSwap.selector;
    }

    /**
     * Helper that runs the InternalSwapPool fast-path during `_beforeSwap`. Extracted to keep the
     * outer hook function below the legacy stack-too-deep threshold.
     *
     * @param _sender The address calling the swap
     * @param _key The key for the pool
     * @param _params The parameters for the swap
     * @param _hookData Arbitrary data handed into the PoolManager by the swapper to be be passed on to the hook
     * @param _nativeIsZero Whether the native token is zero
     * @param _beforeSwapDelta The before swap delta
     *
     * @return beforeSwapDelta_ The before swap delta
     */
    function _processInternalSwap(
        address _sender,
        PoolKey calldata _key,
        SwapParams calldata _params,
        bytes calldata _hookData,
        bool _nativeIsZero,
        BeforeSwapDelta _beforeSwapDelta
    ) internal returns (BeforeSwapDelta beforeSwapDelta_) {
        beforeSwapDelta_ = _beforeSwapDelta;

        (uint tokenIn, uint tokenOut) = internalSwapPool.internalSwap(_key, _params, _nativeIsZero);
        if (tokenIn + tokenOut == 0) {
            return beforeSwapDelta_;
        }

        // The {InternalSwapPool} computed the fill against its fee inventory but, as the swap-delta
        // owner, this hook performs the matching settlement: take the native `tokenIn` from the
        // {PoolManager} and settle the memecoin `tokenOut` back into it.
        poolManager.take(_nativeIsZero ? _key.currency0 : _key.currency1, address(this), tokenIn);
        (_nativeIsZero ? _key.currency1 : _key.currency0).settle(poolManager, address(this), tokenOut, false);

        BeforeSwapDelta internalBeforeSwapDelta = _params.amountSpecified >= 0
            ? toBeforeSwapDelta(-tokenOut.toInt128(), tokenIn.toInt128())
            : toBeforeSwapDelta(tokenIn.toInt128(), -tokenOut.toInt128());

        uint swapFee = _captureAndDepositFees(_key, _params, _sender, internalBeforeSwapDelta.getUnspecifiedDelta(), _hookData);

        _captureDelta(_params, TS_ISP_AMOUNT0, TS_ISP_AMOUNT1, internalBeforeSwapDelta);
        _captureDeltaSwapFee(_params, TS_ISP_FEE0, TS_ISP_FEE1, swapFee);

        beforeSwapDelta_ = toBeforeSwapDelta(
            beforeSwapDelta_.getSpecifiedDelta() + internalBeforeSwapDelta.getSpecifiedDelta(),
            beforeSwapDelta_.getUnspecifiedDelta() + internalBeforeSwapDelta.getUnspecifiedDelta() + swapFee.toInt128()
        );
    }

    /**
     * [FD] Captures fees from the swap to either distribute or send to ISP
     * [ISP] Once a swap has been made, we distribute fees to our LPs and emit our price update event.
     * [FD] Tracks the swap for future fee calculations
     *
     * @param _sender The sender (or swap contract) making the call
     * @param _key The key for the pool
     * @param _params The parameters for the swap
     * @param _delta The amount owed to the caller (positive) or owed to the pool (negative)
     * @param _hookData Arbitrary data handed into the PoolManager by the swapper to be be passed on to the hook
     *
     * @return selector_ The function selector for the hook
     * @return hookDeltaUnspecified_ The hook's delta in unspecified currency. Positive: the hook is owed/took currency,
     * negative: the hook owes/sent currency
     */
    function _afterSwap(
        address _sender,
        PoolKey calldata _key,
        SwapParams calldata _params,
        BalanceDelta _delta,
        bytes calldata _hookData
    ) internal override returns (bytes4 selector_, int128 hookDeltaUnspecified_) {
        /**
         * [FD] We need to determine the amount of fees generated by our Uniswap swap to capture,
         * rather than sending the full amount to the end user.
         */

        // Snapshot the pre-swap tick BEFORE anything below can hand control to token code. Every
        // external call from here on -- the referrer transfer inside `_captureAndDepositFees`,
        // `_allocateFees` inside `_distributeFees` -- can re-enter with a nested swap whose
        // `beforeSwap` overwrites the shared `_beforeSwapTick` slot.
        int24 beforeSwapTick = _beforeSwapTick;

        // Scoped so the swap amounts leave the stack before the calls below: this function sits
        // on the stack-depth limit and the snapshot above needs the room. Ordering is unchanged.
        uint swapFee;
        {
            // Determine the currency that we will be taking our fee from
            (int128 amount0, int128 amount1) = (_delta.amount0(), _delta.amount1());
            int128 swapAmount = _params.amountSpecified < 0 == _params.zeroForOne ? amount1 : amount0;

            // Capture the swap fees and dispatch the referrer's share if set
            swapFee = _captureAndDepositFees(_key, _params, _sender, swapAmount, _hookData);

            // Increment our swap
            assembly {
                tstore(TS_UNI_AMOUNT0, amount0)
                tstore(TS_UNI_AMOUNT1, amount1)
            }
        }

        _captureDeltaSwapFee(_params, TS_UNI_FEE0, TS_UNI_FEE1, swapFee);

        /**
         * [ISP] Distribute any fees that have been converted by the swap.
         */
        _distributeFees(_key, beforeSwapTick);

        /**
         * [FD] If we have a feeCalculator, then we want to track the swap data for any
         * dynamic calculations.
         */
        PoolId poolId = _key.toId();

        {
            IFeeCalculator _feeCalculator = feeCalculator;
            if (address(_feeCalculator) != address(0)) {
                _feeCalculator.trackSwap(_sender, _key, _params, _delta, _hookData);
            }
        }

        // Set our return selector
        hookDeltaUnspecified_ = swapFee.toInt128();

        selector_ = IHooks.afterSwap.selector;

        // Emit our compiled swap data
        _emitSwapUpdate(poolId, _sender);

        // Emit our pool state update to listeners
        _emitPoolStateUpdate(poolId, selector_, abi.encode(_sender, _params, _delta));
    }

    /**
     * Once a liquidity has been added, we emit our price update event.
     *
     * @param _sender The initial msg.sender for the add liquidity call
     * @param _key The key for the pool
     * @param _delta The caller's balance delta after adding liquidity; the sum of principal delta, fees accrued, and
     * hook delta
     * @param _feesAccrued The fees accrued since the last time fees were collected from this position
     *
     * @return selector_ The function selector for the hook
     * @return BalanceDelta The hook's delta in token0 and token1. Positive: the hook is owed/took currency, negative:
     * the hook owes/sent currency
     */
    function _afterAddLiquidity(
        address _sender,
        PoolKey calldata _key,
        ModifyLiquidityParams calldata,
        BalanceDelta _delta,
        BalanceDelta _feesAccrued,
        bytes calldata
    ) internal override returns (bytes4 selector_, BalanceDelta) {
        selector_ = IHooks.afterAddLiquidity.selector;

        // Emit our pool state update to listeners
        _emitPoolStateUpdate(_key.toId(), selector_, abi.encode(_sender, _delta, _feesAccrued));
    }

    /**
     * Once liquidity has been removed, we emit our price update event.
     *
     * @param _sender The initial msg.sender for the remove liquidity call
     * @param _key The key for the pool
     * @param _delta The caller's balance delta after removing liquidity; the sum of principal delta, fees accrued, and
     * hook delta
     * @param _feesAccrued The fees accrued since the last time fees were collected from this position
     *
     * @return selector_ The function selector for the hook
     */
    function _afterRemoveLiquidity(
        address _sender,
        PoolKey calldata _key,
        ModifyLiquidityParams calldata,
        BalanceDelta _delta,
        BalanceDelta _feesAccrued,
        bytes calldata
    ) internal override returns (bytes4 selector_, BalanceDelta) {
        selector_ = IHooks.afterRemoveLiquidity.selector;

        // Emit our pool state update to listeners
        _emitPoolStateUpdate(_key.toId(), selector_, abi.encode(_sender, _delta, _feesAccrued));
    }

    /**
     * The hook called after donate, emitting our price update event.
     *
     * @param _sender The initial msg.sender for the donate call
     * @param _key The key for the pool
     * @param _amount0 The amount of token0 being donated
     * @param _amount1 The amount of token1 being donated
     *
     * @return selector_ The function selector for the hook
     */
    function _afterDonate(
        address _sender,
        PoolKey calldata _key,
        uint _amount0,
        uint _amount1,
        bytes calldata
    ) internal override returns (bytes4 selector_) {
        selector_ = IHooks.afterDonate.selector;

        // Emit our pool state update to listeners
        _emitPoolStateUpdate(_key.toId(), selector_, abi.encode(_sender, _amount0, _amount1));
    }

    /**
     * Gets the ETH fee that must be paid to flaunch a token.
     *
     * @return The ETH value of the fee
     */
    function getFlaunchingFee(
        bytes calldata _initialPriceParams
    ) public view returns (uint) {
        return initialPrice.getFlaunchingFee(msg.sender, _initialPriceParams);
    }

    /**
     * Gets the ETH market cap for a new token that will be flaunched.
     *
     * @return The ETH market cap value
     */
    function getFlaunchingMarketCap(
        bytes calldata _initialPriceParams
    ) public view returns (uint) {
        return initialPrice.getMarketCap(_initialPriceParams);
    }

    /**
     * Allows the contract used to flaunch a new token to be updated.
     *
     * @param _flaunchContract The new {IFlaunch} contract address
     */
    function setFlaunch(
        address _flaunchContract
    ) public onlyOwner {
        flaunchContract = IFlaunch(_flaunchContract);
    }

    /**
     * Updates the `IInitialPrice` contract address that is used during `flaunch` to calculate
     * the initial tick / sqrtPriceX96 value.
     *
     * @param _initialPrice The contract address for the `IInitialPrice` contract
     */
    function setInitialPrice(
        address _initialPrice
    ) public onlyOwner {
        initialPrice = IInitialPrice(_initialPrice);
        emit InitialPriceUpdated(_initialPrice);
    }

    /**
     * Calls for the BidWall to be closed, as this requires callback from the {PoolManager}.
     */
    function closeBidWall(
        PoolKey memory _key
    ) public {
        // Ensure that the call is made by the BidWall which validates logic
        if (msg.sender != address(bidWall)) {
            revert CallerIsNotBidWall();
        }

        // Ensure that the PoolKey that is being closed is valid and recognised on the protocol,
        // otherwise we could processing issues and false positives in upcoming steps. We need to
        // ensure that the PoolKey is recognised (by checking the hooks address is not zero) and
        // that the PoolId matches when encoded.
        PoolKey memory storedKey = _poolKeys[address(_key.memecoin(pairedToken(_key.toId())))];
        if (storedKey.hooks == IHooks(address(0)) || PoolId.unwrap(storedKey.toId()) != PoolId.unwrap(_key.toId())) {
            revert UnknownPool(_key.toId());
        }

        // Action our BidWall closure via the {PoolManager} unlock
        _closeBidWall(_key);
    }

    /**
     * Unwinds the BidWall position for a pool via a {PoolManager} unlock.
     *
     * @dev The caller is responsible for validating the `PoolKey` before this is reached.
     *
     * @param _poolKey The PoolKey to close the BidWall of
     */
    function _closeBidWall(
        PoolKey memory _poolKey
    ) internal override {
        poolManager.unlock(abi.encode(UnlockCallbackType.CLOSE_BIDWALL, abi.encode(_poolKey)));
    }

    /**
     * Handles the unlock callback for the {PoolManager} interactions.
     *
     * @param _data The encoded data for the unlock callback
     *
     * @return bytes The data to be returned from the unlock callback
     */
    function _unlockCallback(
        bytes calldata _data
    ) internal override returns (bytes memory) {
        // Decode the data to determine the action and payload
        (UnlockCallbackType _action, bytes memory _payload) = abi.decode(_data, (UnlockCallbackType, bytes));

        // Check if we are closing the BidWall
        if (_action == UnlockCallbackType.CLOSE_BIDWALL) {
            bidWall.closeBidWall(abi.decode(_payload, (PoolKey)));
            return '';
        }
        // Check if we are seeding the liquidity and premine
        else if (_action == UnlockCallbackType.FLAUNCH_LIQUIDITY) {
            return _seedLiquidityAndPremine(_payload);
        }

        // Return empty data if we haven't matched any of the actions
        return '';
    }

    /**
     * Seeds a freshly flaunched pool with its initial single-sided liquidity and, if requested,
     * fills a premine for the creator. Runs inside the {PoolManager} unlock context.
     *
     * The full token supply is held by this contract following the flaunch. We seed the supply as
     * a single-sided memecoin sell position and, if a premine was requested, swap against that
     * position to deliver the premined tokens to the creator. Any flETH we wrapped but did not end
     * up spending on the premine is unwrapped back into ETH so {flaunch} can refund the caller.
     *
     * @param _payload ABI-encoded `(address memecoin, address creator, address payer, uint premineAmount, uint remainingValue, uint maxPremineCost)`
     *
     * @return amountSpent_ ABI-encoded amount of ETH consumed by the premine swap (zero for an
     * ERC20-paired premine, which is funded in the paired token rather than ETH)
     */
    function _seedLiquidityAndPremine(
        bytes memory _payload
    ) internal returns (bytes memory amountSpent_) {
        // Decode the payload to provide the required information
        (address memecoin, address creator, address payer, uint premineAmount, uint remainingValue, uint maxPremineCost) =
            abi.decode(_payload, (address, address, address, uint, uint, uint));

        // Resolve the pool key and determine if the native token is the zero token
        PoolKey memory _poolKey = _poolKeys[memecoin];
        PoolId poolId = _poolKey.toId();
        address paired = pairedToken(poolId);

        // Both the seeding and the premine run in the linked {FlaunchLibrary}: their bytecode is
        // sizeable and lives at the library's own address rather than inside this hook, which sits
        // against the EIP-170 limit. The library is reached by `delegatecall`, so it creates the
        // position and settles from this contract's balances exactly as if it were inlined. The
        // paired token's shape comes from this pool's frozen launch-time snapshot (never the live
        // registry), so a later registry change cannot alter how an existing pool premines.
        amountSpent_ = abi.encode(
            FlaunchLibrary.seedLiquidityAndPremine(
                FlaunchLibrary.SeedParams({
                    poolManager: poolManager,
                    poolKey: _poolKey,
                    initialTick: initialPoolTick[poolId],
                    nativeIsZero: paired == Currency.unwrap(_poolKey.currency0),
                    tokenType: _pairedTokenConfig[poolId].tokenType,
                    paired: paired,
                    memecoin: memecoin,
                    creator: creator,
                    payer: payer,
                    premineAmount: premineAmount,
                    remainingValue: remainingValue,
                    maxPremineCost: maxPremineCost
                })
            )
        );
    }

    /**
     * Whether a pool's paired token is raw native ETH (`address(0)`), read from the pool's
     * launch-time snapshot. A native-ETH pool settles its paired side directly in ETH, so premine
     * funds from `msg.value` without any wrap and the BidWall / escrow move value rather than an ERC20.
     *
     * @param _poolId The pool whose paired token is being checked
     *
     * @return Whether the pool's paired token is raw native ETH
     */
    function _isNativeEth(
        PoolId _poolId
    ) internal view returns (bool) {
        return _pairedTokenConfig[_poolId].tokenType == IPairedTokenRegistry.PairedTokenType.NativeEth;
    }

    /**
     * Capture the fees from our swap. This could either be from an internal swap (`beforeSwap`)
     * or from the actual Uniswap swap (`afterSwap`).
     *
     * @dev This is only used due to too many variables in the `beforeSwap` function
     *
     * @param _key The {PoolKey} that the swap was made against
     * @param _params The swap parameters called in the swap
     * @param _sender The sender of the swap call
     * @param _delta The balance change from the swap
     * @param _hookData Additional bytes data passed in the swap
     *
     * @return swapFee_ The fee taken from the swap
     */
    function _captureAndDepositFees(
        PoolKey calldata _key,
        SwapParams memory _params,
        address _sender,
        int128 _delta,
        bytes calldata _hookData
    ) internal returns (uint swapFee_) {
        // Determine the swap fee currency based on swap parameters
        Currency swapFeeCurrency = _params.amountSpecified < 0 == _params.zeroForOne ? _key.currency1 : _key.currency0;

        // Capture our swap fees amount
        swapFee_ = _captureSwapFees({
            _poolManager: poolManager,
            _key: _key,
            _params: _params,
            _feeCalculator: feeCalculator,
            _swapFeeCurrency: swapFeeCurrency,
            _swapAmount: uint128(_delta < 0 ? -_delta : _delta),
            _feeExemption: feeExemptions.feeExemption(_sender)
        });

        // If we have no swap fees, then we have nothing to process
        if (swapFee_ == 0) {
            return swapFee_;
        }

        // Check if we have a referrer set and send them the currency directly
        uint referrerFee =
            _distributeReferrerFees({_key: _key, _swapFeeCurrency: swapFeeCurrency, _swapFee: swapFee_, _hookData: _hookData});

        // Deposit the remaining fees against our pool to be either distributed to
        // others, or placed into the Internal Swap Pool to be converted into the paired
        // token. We don't reduce the amount by referrer fees as we still need to claim
        // this from the PoolManager. `amount0` is always the paired-token side.
        bool feeIsPairedSide = Currency.unwrap(swapFeeCurrency) == pairedToken(_key.toId());
        uint depositAmount = swapFee_ - referrerFee;
        internalSwapPool.depositFees(_key, feeIsPairedSide ? depositAmount : 0, feeIsPairedSide ? 0 : depositAmount);
    }

    /**
     * We want to be able to distribute fees across our {FeeDistribution} recipients
     * when we reach a set threshold. This will only ever distribute the ETH equivalent
     * token, as the non-ETH token will be converted via the {InternalSwapPool} hook logic.
     *
     * @dev There referrer has already received their share, so they do not need to be
     * taken into account at this point.
     *
     * @param _poolKey The PoolKey reference that will have fees distributed
     * @param _swapTick The pre-swap tick, snapshotted by {_afterSwap} before any external call
     * could have overwritten the shared `_beforeSwapTick` slot
     */
    function _distributeFees(
        PoolKey memory _poolKey,
        int24 _swapTick
    ) internal {
        PoolId poolId = _poolKey.toId();

        // Get the amount of the paired token available to distribute
        uint distributeAmount = internalSwapPool.poolFees(_poolKey).amount0;

        // Ensure that the collection has sufficient fees available. The threshold is read from the
        // pool's launch-time snapshot (decimals-aware per paired token), falling back to the
        // protocol default for flETH.
        if (distributeAmount < _minDistributeThreshold(poolId)) {
            return;
        }

        // Reduce our available fees for the pool
        internalSwapPool.resetNativeFees(poolId);

        // Find the distribution amount across our different users. The amount that treasury
        // receives will be determined by variables throughout the distribution flow, such as
        // the BidWall being disabled, etc.
        (uint bidWallFee, uint creatorFee, uint protocolFee) = feeSplit(poolId, distributeAmount);
        uint treasuryFee;

        // Load our paired token; the memecoin is derived from it at each use rather than held in
        // a local, because this function sits on the stack-depth limit and `_swapTick` needs the
        // room. `memecoin()` is a pure {PoolKey} accessor, so re-deriving it costs no storage read.
        address paired = pairedToken(poolId);

        // [F-9] The Flaunch NFT is a bearer instrument: whoever holds it right now is the
        // creator that fees should route to. Read `memecoin.creator()` live at each decision
        // point rather than caching once across external calls. Defends against any future
        // call-path that could change ownership between branches (e.g. an ERC721 receiver
        // hook on a buyer's transferFrom callback flipping the NFT mid-distribution).

        if (creatorFee != 0) {
            address creatorNow = _memecoinCreator(address(_poolKey.memecoin(paired)));
            // Ensure that the pool creator has not burned their ownership and send them the fees
            if (creatorNow != address(0)) {
                _allocateFees(poolId, creatorNow, creatorFee);
            }
            // If the pool creator has burned their ownership, then we instead send fees directly
            // to the BidWall.
            else {
                bidWallFee += creatorFee;
                creatorFee = 0;
            }
        }

        if (bidWallFee != 0) {
            // Check if we have an active BidWall for the pool. If we don't have an active BidWall, then
            // we will need to instead allocate this to the protocol.
            if (bidWall.isBidWallEnabled(poolId)) {
                // Otherwise, we can deposit directly into the BidWall as we have permission to modify
                // liquidity outside of the window. A native-ETH pool pushes the fee as value so the
                // BidWall custodies it; an ERC20 pool leaves the fee in this hook (the BidWall pulls
                // it via the allowance set in {_ensureBidWallApproval}).
                // [L-2] Re-assert the BidWall's allowance before it pulls. `ensureBidWallApproval`
                // otherwise runs only at LAUNCH, so an allowance-decrementing paired token drains
                // the grant over the pool's life and the reposition eventually reverts inside
                // `afterSwap` -- permanently, by H-2's rollback mechanics, with no owner recovery.
                // This mirrors the `< amount` self-heal `_allocateFees` already performs. Called
                // unconditionally: the library no-ops for raw native ETH, and for any token
                // honouring a `type(uint).max` allowance the sentinel check never fires.
                FlaunchLibrary.ensureBidWallApproval(address(bidWall), paired);

                uint bidWallValue = _isNativeEth(poolId) ? bidWallFee : 0;
                bidWall.deposit{value: bidWallValue}(_poolKey, bidWallFee, _swapTick, paired == Currency.unwrap(_poolKey.currency0));
            } else {
                // If we cannot import into BidWall, then treasury will be allocated the fees
                treasuryFee += bidWallFee;
                bidWallFee = 0;
            }
        }

        if (treasuryFee != 0) {
            // Re-read the live creator to settle the treasury branch: a burn that happens
            // between the creator-fee allocation and here must route through to the protocol.
            if (_memecoinCreator(address(_poolKey.memecoin(paired))) != address(0)) {
                _allocateFees(poolId, _poolKey.memecoin(paired).treasury(), treasuryFee);
            } else {
                // If we cannot allocate to treasury, then protocol receives the fees
                protocolFee += treasuryFee;
                treasuryFee = 0;
            }
        }

        // Finally we allocate our protocol fees
        if (protocolFee != 0) {
            _allocateFees(poolId, protocolFeeRecipient, protocolFee);
        }

        emit PoolFeesDistributed(poolId, distributeAmount, creatorFee, bidWallFee, treasuryFee, protocolFee);
    }

    /**
     * Using the `tstore` values that we have generated along the way, we emit an event that shows
     * the breakdown of fees earned at each swap point.
     *
     * @dev Delegated to the linked {FlaunchLibrary}. The eighteen `tload`s and the thirteen-field
     * {PoolSwap} emit compile to roughly a kilobyte of bytecode that this hook — which sits against
     * the EIP-170 limit — cannot afford to carry. `delegatecall` keeps the executing address as
     * this contract, so the transient slots read and cleared are this hook's own and the logs are
     * emitted under this hook's address, byte-for-byte as before.
     *
     * @param _poolId The PoolId that is being emitted
     * @param _sender The router of the swap
     */
    function _emitSwapUpdate(
        PoolId _poolId,
        address _sender
    ) internal {
        FlaunchLibrary.emitSwapUpdate(_poolId, _sender);
    }

    /**
     * Emits an event that provides pool state updates and passes the data to subscribers.
     *
     * @dev Delegated to the linked {FlaunchLibrary} so the two {PoolManager} state reads and the
     * six-field event emit are deployed at the library's address rather than in this hook, which
     * sits against the EIP-170 limit. Kept behind this wrapper (rather than delegating from each of
     * the five call sites) so only one delegated call frame is paid for.
     *
     * @param _poolId The PoolId that has been updated
     * @param _key The selector being sent to notification subscribers
     * @param _data The data being sent to notification subscribers
     */
    function _emitPoolStateUpdate(
        PoolId _poolId,
        bytes4 _key,
        bytes memory _data
    ) internal {
        FlaunchLibrary.emitPoolStateUpdate(poolManager, address(notifier), _poolId, _key, _data);
    }

    /**
     * Settles tokens against the PoolManager based on the BalanceDelta passed.
     *
     * @dev This is required to be separated due to Stack Too Deep errors
     *
     * @param _poolKey The pool key to settle against
     * @param _delta The BalanceDelta showing token amounts to settle
     */
    function _settleDelta(
        PoolKey memory _poolKey,
        BalanceDelta _delta
    ) internal {
        if (_delta.amount0() < 0) {
            _poolKey.currency0.settle(poolManager, address(this), uint(-int(_delta.amount0())), false);
        } else if (_delta.amount0() > 0) {
            poolManager.take(_poolKey.currency0, address(this), uint(int(_delta.amount0())));
        }

        if (_delta.amount1() < 0) {
            _poolKey.currency1.settle(poolManager, address(this), uint(-int(_delta.amount1())), false);
        } else if (_delta.amount1() > 0) {
            poolManager.take(_poolKey.currency1, address(this), uint(int(_delta.amount1())));
        }
    }

    /**
     * We need to be able to set the (un)specified token to amount0 / amount1 for the expected
     * event emit format.
     *
     * @param _params The `SwapParams` used to capture the delta
     * @param _key_amount0 The tstore key for the token0 amount
     * @param _key_amount1 The tstore key for the token1 amount
     * @param _delta The `BeforeSwapDelta` that is being captured
     */
    function _captureDelta(
        SwapParams memory _params,
        bytes32 _key_amount0,
        bytes32 _key_amount1,
        BeforeSwapDelta _delta
    ) internal {
        (int token0, int token1) = _params.amountSpecified < 0 == _params.zeroForOne
            ? (-_delta.getSpecifiedDelta(), -_delta.getUnspecifiedDelta())
            : (-_delta.getUnspecifiedDelta(), -_delta.getSpecifiedDelta());

        // Store our amounts
        assembly {
            tstore(_key_amount0, token0)
            tstore(_key_amount1, token1)
        }
    }

    /**
     * Maps our swap fee to the expected event emit format.
     *
     * @param _params The `SwapParams` used to capture the delta
     * @param _key_fee0 The tstore key for the token0 fee amount
     * @param _key_fee1 The tstore key for the token1 fee amount
     * @param _delta The `uint` that is being captured for the fee
     */
    function _captureDeltaSwapFee(
        SwapParams memory _params,
        bytes32 _key_fee0,
        bytes32 _key_fee1,
        uint _delta
    ) internal {
        // The delta provided needs to be made negative
        int delta = -int(_delta);

        if (_params.amountSpecified < 0 == _params.zeroForOne) {
            assembly {
                tstore(_key_fee0, 0)
                tstore(_key_fee1, delta)
            }
        } else {
            assembly {
                tstore(_key_fee0, delta)
                tstore(_key_fee1, 0)
            }
        }
    }

    /**
     * Helper function to allow for tstore-d variables to be called individually. This saves us
     * defining an additional variable before our `tload` calls inside the function.
     *
     * @param _key The `tstore` key to load
     *
     * @return value_ The `int` value in the tstore
     */
    function _tload(
        bytes32 _key
    ) internal view returns (int value_) {
        assembly {
            value_ := tload(_key)
        }
    }
}
